### PR TITLE
fix: n-way-dimmer sync problem

### PR DESCRIPTION
**Pull request by JeremyYu-cn**
## Rewrite and fixed n-way-dimmer synchronization problem.

### CODE REVIEW

**Comment by taulfsime** [comment]
Thank you.

**Comment by chrispo-m** [comment]
@JeremyYu-cn - thanks a bunch.  

I'm running your revision on a group of two devices and so far it looks solid.  I'll continue to exercise the code and post an update.

I appreciate your quick help - this script adds some great functionality to these dimmers.

**Comment by chrispo-m** [comment]
I did unfortunately find a way to break it.

If one swipes the touch dimmer quickly several times it appears the code may be trying to transmit a whole bunch of new dimmer values.  A worthwhile improvement would be some "if n dimmer setting changes in the last x milliseconds, then wait till it stops changing and send only the last" 

The console error is "Uncaught Error: Too many calls in progress"

I'll look in to implementing this, but as I'm not a js programmer in the least I'm not confident in contributing any changes to the codebase.

**Comment by taulfsime** [comment]
@chrispo-m 
Sure, thank you. Please try to handle it yourself; we can support you if needed.

**Pull request merged**
