### PR TITLE
feature: add a universal-blu-to-mqtt script example

### PR DESCRIPTION
**Pull request by JeremyYu-cn**
### Short description

  - This script is about shares any BLU product's complete payload to MQTT.

  - The script should not require an individual BLU device's MAC address, rather it will "listen" for any BLU device.

  - It would use the MAC address to create the topic, with a key-value for each data point in the payload.

### CODE REVIEW

**Comment by taulfsime** [comment]
Thank you, it's perfect, please just add it in the README as well.

**Comment by JeremyYu-cn** [comment]
Added update log on README.md

**Comment by taulfsime** [comment]
lgtm, thanks.

**Comment by Vanuan** [comment]
Doesn't appear to have a correct BTH map:
https://shelly-api-docs.shelly.cloud/docs-ble/Devices/ht/

Found on reddit: https://www.reddit.com/r/ShellyUSA/comments/1h9sw5r/comment/m17omcu/?context=3

**Comment by JeremyYu-cn** [comment]
Hi, @Vanuan
Thanks for providing this problem. I think I've defined an incomplete BTH decoding object.

image

This is the correct one. I'll create a pull request and fix it.

**Pull request merged**
