### PR TITLE
Create n-way-dimmer.js

### PR DESCRIPTION
**Pull request by tscofield**
N-Way Dimmer will synchronize the dimmer values between multiple Shelly Plus Wall Dimmers. Only one Dimmer is connected to the load, all the rest are used only for control. This removes the need for any cloud services or home automation system to keep them in sync.

### CODE REVIEW

**Comment by Mircho** [comment]
Thank you for this script. Pretty advanced implementation!

Can you add a record in https://github.com/ALLTERCO/shelly-script-examples/blob/main/SHELLY_MJS.md?

**Comment by tscofield** [comment]
Will do, I need to make a tweak to the code, I was hoping not to have to poll for the dimer value changes, but upon further testing, right now only on/off get synced real time, the brightness value only gets synced on power off which is less than ideal.

**Comment by tscofield** [comment]
I have updated the SHELLY_MJS.md as requested, I had to abandon plans to poll for dimmer changes and will have to reevaluate how to implement that feature. The code as it is now will at least provide basic functionality.

**Comment by Mircho** [comment]
Thank you.

**Pull request merged**
